name: material_map
description: "Material Map - Find products and compare prices at nearby stores."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  # HTTP and API
  http: ^1.1.0
  dio: ^5.3.1

  # State Management
  provider: ^6.1.2

  # UI
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  lottie: ^3.3.1

  # Utils
  shared_preferences: ^2.3.5
  intl: ^0.19.0
  geolocator: ^13.0.2
  jwt_decoder: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/


